use_frameworks!

platform :ios, '11.0'

target 'MineLib_Example' do
  pod 'MineLib', :path => '../'
  pod 'CommonLib', :path => '../../CommonLib'
  target 'MineLib_Tests' do
    inherit! :search_paths

    
  end
end
