# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'MainProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'CommonLib', :path => '../CommonLib'
	pod 'HomeLib', :path => '../HomeLib'
  pod 'MineLib', :path => '../MineLib'
  # Pods for MainProject

end
