use_frameworks!

platform :ios, '11.0'

target 'HomeLib_Example' do
  pod 'HomeLib', :path => '../'
  pod 'CommonLib', :path => '../../CommonLib'
  target 'HomeLib_Tests' do
    inherit! :search_paths

    
  end
end
